language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("WaveletTrees"); Pkg.test("WaveletTrees"; coverage=true)'
after_success:
   - julia -e 'cd(Pkg.dir("WaveletTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
